package com.stadiummate.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A single step in a computed route — one node transition.
 *
 * <p>Steps are assembled by {@link com.stadiummate.service.RouteService}
 * during path reconstruction and included in the {@link RouteResult} returned
 * to the frontend. Each step drives one bullet in the turn-by-turn list.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RouteStep {

    /** Node ID at this step, e.g. {@code "CONC_MAIN_NE"}. */
    @JsonProperty("nodeId")
    private String nodeId;

    /** Display name for the step, e.g. {@code "Northeast Concourse"}. */
    @JsonProperty("nodeName")
    private String nodeName;

    /**
     * Human-readable turn-by-turn instruction generated by the route engine.
     * Examples: "Head north along the East Concourse", "Take the elevator up".
     */
    @JsonProperty("instruction")
    private String instruction;

    /**
     * Edge type used to reach this node: {@code walk}, {@code elevator},
     * {@code ramp}. Frontend uses this to pick the step icon.
     */
    @JsonProperty("edgeType")
    private String edgeType;

    /**
     * Actual (un-weighted) distance in metres from the previous step.
     * Zero for the first step (departure node).
     */
    @JsonProperty("distanceFromPrevious")
    private double distanceFromPrevious;
}
